### ISSUE TITLE
Plugin code review

### ISSUE THREAD

**Issue by kadamwhite** [thinkstylestudio/WpApiAddHashToAttachment#1]
This is a belated follow-up from a [request for code review](https://wordpress.slack.com/archives/C02RQC26G/p1496464540448399) in the WordPress slack rest API channel. Hope this helps!

In general this seems both interesting and useful. Some comments on the specific implementation:

### registered field description clarity

Inside the `register_rest_field`'s `schema` property, I see the key
```php
'description' => __( 'Comment media_file_md5.' ),
```
This doesn't seem to be the most applicable description. Something like "MD5 hash of media file" might be more easily understood.

### function naming

The functions defined by this plugin should be consistently prefixed. Since you use `rest_api_media_hash_activation`, perhaps they should all be `rest_api_media_hash_XXXXX` -- or if that is too verbose, `api_media_hash_XXXX` or something.

This would make the function name `add_hash_to_attachment_post_meta` change to something like `[yourprefix]_add_hash_to_attachment_post_meta`. (For simplicity when reading the code, I would also declare this function before it is used.)

Regarding the specific function `insert_custom_default_caption`, I think a better name might be something like `[yourprefix]_update_md5_hash`: the caption is not being altered so the existing name is misleading.

### updating md5 for a non-existent file

I notice that in `add_hash_to_attachment_post_meta`, if the file does not exist, the function does nothing. This could result in situations where an attachment was uploaded, and given a valid `_attachment_file_hash` meta key; then the file was deleted, and when the function was re-run the `_attachment_file_hash` would still reflect the now-missing file. Would it be better to delete the `_attachment_file_hash` key if the file does not exist, since an accurate comparison cannot be made?

### activation performance

Finally, I would suggest testing this out on a large site with many images; I'd be concerned that the `rest_api_media_hash_activation` activation hook could be an expensive operation, and I'd want to validate that it executes correctly at scale.

**Comment by thinkstylestudio** [comment]
This is great @kadamwhite thank you very much for the review. My response is quite late of course but the feedback has none the less gone to waste.
